### PR TITLE
Fix concurrency handling in CircularArray.GetTail

### PR DESCRIPTION
**Pull request by markvincze**
This was causing actual `IndexOutOfRangeException`s being thrown.

### CODE REVIEW

**Comment by JorritSalverda** [comment]
Ah, we've been seeing those for years. Nice improvement.

**Review by JorritSalverda — APPROVED** [review]

**Comment by JorritSalverda** [comment]
I'm trying to find the original implementation in Netflix's version, but I can't find the source code for the used [BucketCircularArray](https://github.com/Netflix/Hystrix/search?utf8=%E2%9C%93&q=BucketCircularArray&type=) they use in their RollingNumber and RollingPercentile.

**Comment by JorritSalverda** [comment]
Ah, it's just Github's search that sucks. Here's the code:

https://github.com/Netflix/Hystrix/blob/d838f4d1ba65ce55755ab1c73f74c980f04572bf/hystrix-core/src/main/java/com/netflix/hystrix/util/HystrixRollingNumber.java#L539-L546

**Comment by markvincze** [comment]
Thanks @lucaslorentz for catching this issue!

**Comment by markvincze** [comment]
Interesting, the AppVeyor build fails with an unrelated issue, and it also fails on my machine. I think some of the packages were changed on Nuget (something was maybe removed?), and that broke our build. I'm checking locally.

**Pull request merged**
