### PR TITLE
Fix all the sample projects

### PR DESCRIPTION
**Pull request by markvincze**
Addresses #12

### CODE REVIEW

**Comment by HigorCesar** [comment]
@markvincze the solution is working perfectly with `dotnet run` but It is hanging when I try to run with VisualStudio. Could you test in your environment?
Another point that can/should be addressed in another issue is the weird namespace of the HelloController inside ASP.NetCore sample.

**Review by HigorCesar — COMMENTED** [review]
@markvincze the solution is working perfectly with `dotnet run` but It is hanging when I try to run with VisualStudio. Could you test in your environment?
Another point that can/should be addressed in another issue is the weird namespace of the HelloController inside ASP.NetCore sample.

**Comment by markvincze** [comment]
I fixed the namespace, but couldn't reproduce the hang, for me it works.
What does it do, actually VS doesn't respond, or it keeps spinning the progress indicator?

**Comment by HigorCesar** [comment]
@markvincze I tried to clean and change the build configuration but I still can't run it. I think that it could be some machine configuration, as It is working for everyone else I would not spend more time debugging. Therefore your PR looks good to merge.
vshanging

**Pull request merged**
