### PR TITLE
Update mvc dependency in sample to remove vulnerability warning

### PR DESCRIPTION
**Pull request by baor**

### CODE REVIEW

**Comment by Prutswonder** [comment]
👍

**Comment by markvincze** [comment]
Thanks! 👍 
It's weird that one of the builds out of the two is failing (especially because those should be identical I think), maybe one of our tests is not isolated enough, so it fails randomly? I'll try to check.

**Comment by markvincze** [comment]
I could reproduce the failure locally, and indeed it's random, sometimes it fails, sometimes it passes.

I'll look into what this test is doing, and will try to fix it.

**Comment by markvincze** [comment]
Ok, I think what the problem is that the [Dictionary we store the commands in](https://github.com/Travix-International/Hystrix.Dotnet/blob/master/src/Hystrix.Dotnet/HystrixCommandFactory.cs#L12) is static. And Xunit by default is running the tests in parallel, so sometimes by chance tests step on each other's feet.

I added [this commit](https://github.com/Travix-International/Hystrix.Dotnet/pull/28/commits/384031da33af6da0b02dbe76da86f3d24cf4a4da) to the branch to prevent the tests from failing.

I know that this is just hiding the symptom rather than a proper solution, but I don't want to spend more time on it now. (Probably that dictionary should be changed to be non-static, but I don't know what effects that would have.)  
cc @JorritSalverda

**Review by markvincze — APPROVED** [review]

**Comment by baor** [comment]
thank you, @markvincze !

**Pull request merged**
